apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  labels:
    app: social-media-producer
    tier: ingestion
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC: "social-media-posts"
  DATA_SOURCE: "reddit"
  REDDIT_SUBREDDITS: "technology+datascience+programming+aws+kubernetes+artificial"
  POLL_INTERVAL_SEC: "3.0"
  MAX_RETRIES: "10"
  BASE_RETRY_DELAY_SEC: "1.0"
  MAX_RETRY_DELAY_SEC: "30.0"
