apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  labels:
    app: social-media-producer
    tier: ingestion
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC: "social-media-posts"
  MESSAGE_INTERVAL_SEC: "1.5"
  MAX_RETRIES: "20"
  RETRY_DELAY_SEC: "5"
